//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php", ConfigurationName="FormularioAvaliacaoAOBrazip.FormularioAvaliacaoAOPort")]
    public interface FormularioAvaliacaoAOPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php#in" +
            "serir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.InserirResult inserir(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.InserirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php#in" +
            "serir", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.InserirResult> inserirAsync(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.InserirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php#ob" +
            "ter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterResult obter(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php#ob" +
            "ter", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterResult> obterAsync(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php#ob" +
            "terLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterListaResult obterLista(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php#ob" +
            "terLista", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterListaResult> obterListaAsync(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterListaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class InserirRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InserirRequestDados dadosField;
        
        private string siglaField;
        
        private string servicekeyField;
        
        private string hashField;
        
        private System.Nullable<int> posicaoinicialField;
        
        private System.Nullable<int> quantidadeField;
        
        private string parametro_testeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public InserirRequestDados dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
                this.RaisePropertyChanged("dados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sigla {
            get {
                return this.siglaField;
            }
            set {
                this.siglaField = value;
                this.RaisePropertyChanged("sigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string servicekey {
            get {
                return this.servicekeyField;
            }
            set {
                this.servicekeyField = value;
                this.RaisePropertyChanged("servicekey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> posicaoinicial {
            get {
                return this.posicaoinicialField;
            }
            set {
                this.posicaoinicialField = value;
                this.RaisePropertyChanged("posicaoinicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string parametro_teste {
            get {
                return this.parametro_testeField;
            }
            set {
                this.parametro_testeField = value;
                this.RaisePropertyChanged("parametro_teste");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class InserirRequestDados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> bzpcodclienteField;
        
        private System.Nullable<int> bzpcodempresaField;
        
        private string bzpdataField;
        
        private string bzprecursoField;
        
        private string bzpcodigoreferenciaField;
        
        private System.Nullable<int> avaliacaoField;
        
        private string comentarioField;
        
        private System.Nullable<int> solicitacaoatendidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bzpcodcliente {
            get {
                return this.bzpcodclienteField;
            }
            set {
                this.bzpcodclienteField = value;
                this.RaisePropertyChanged("bzpcodcliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bzpcodempresa {
            get {
                return this.bzpcodempresaField;
            }
            set {
                this.bzpcodempresaField = value;
                this.RaisePropertyChanged("bzpcodempresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzpdata {
            get {
                return this.bzpdataField;
            }
            set {
                this.bzpdataField = value;
                this.RaisePropertyChanged("bzpdata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzprecurso {
            get {
                return this.bzprecursoField;
            }
            set {
                this.bzprecursoField = value;
                this.RaisePropertyChanged("bzprecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzpcodigoreferencia {
            get {
                return this.bzpcodigoreferenciaField;
            }
            set {
                this.bzpcodigoreferenciaField = value;
                this.RaisePropertyChanged("bzpcodigoreferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> avaliacao {
            get {
                return this.avaliacaoField;
            }
            set {
                this.avaliacaoField = value;
                this.RaisePropertyChanged("avaliacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> solicitacaoatendida {
            get {
                return this.solicitacaoatendidaField;
            }
            set {
                this.solicitacaoatendidaField = value;
                this.RaisePropertyChanged("solicitacaoatendida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class ObterListaResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObterResultDados[] dadosField;
        
        private string statusRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ObterResultDados[] dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
                this.RaisePropertyChanged("dados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusRetorno {
            get {
                return this.statusRetornoField;
            }
            set {
                this.statusRetornoField = value;
                this.RaisePropertyChanged("statusRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class ObterResultDados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> bzpcodlancaField;
        
        private string bzpdataField;
        
        private string bzprecursoField;
        
        private string bzpcodigoreferenciaField;
        
        private System.Nullable<int> avaliacaoField;
        
        private string comentarioField;
        
        private System.Nullable<int> solicitacaoatendidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bzpcodlanca {
            get {
                return this.bzpcodlancaField;
            }
            set {
                this.bzpcodlancaField = value;
                this.RaisePropertyChanged("bzpcodlanca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzpdata {
            get {
                return this.bzpdataField;
            }
            set {
                this.bzpdataField = value;
                this.RaisePropertyChanged("bzpdata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzprecurso {
            get {
                return this.bzprecursoField;
            }
            set {
                this.bzprecursoField = value;
                this.RaisePropertyChanged("bzprecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzpcodigoreferencia {
            get {
                return this.bzpcodigoreferenciaField;
            }
            set {
                this.bzpcodigoreferenciaField = value;
                this.RaisePropertyChanged("bzpcodigoreferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> avaliacao {
            get {
                return this.avaliacaoField;
            }
            set {
                this.avaliacaoField = value;
                this.RaisePropertyChanged("avaliacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> solicitacaoatendida {
            get {
                return this.solicitacaoatendidaField;
            }
            set {
                this.solicitacaoatendidaField = value;
                this.RaisePropertyChanged("solicitacaoatendida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class ObterListaRequestDados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> bzpcodlancaField;
        
        private string bzpdataField;
        
        private string bzprecursoField;
        
        private string bzpcodigoreferenciaField;
        
        private System.Nullable<int> avaliacaoField;
        
        private string comentarioField;
        
        private System.Nullable<int> solicitacaoatendidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bzpcodlanca {
            get {
                return this.bzpcodlancaField;
            }
            set {
                this.bzpcodlancaField = value;
                this.RaisePropertyChanged("bzpcodlanca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzpdata {
            get {
                return this.bzpdataField;
            }
            set {
                this.bzpdataField = value;
                this.RaisePropertyChanged("bzpdata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzprecurso {
            get {
                return this.bzprecursoField;
            }
            set {
                this.bzprecursoField = value;
                this.RaisePropertyChanged("bzprecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzpcodigoreferencia {
            get {
                return this.bzpcodigoreferenciaField;
            }
            set {
                this.bzpcodigoreferenciaField = value;
                this.RaisePropertyChanged("bzpcodigoreferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> avaliacao {
            get {
                return this.avaliacaoField;
            }
            set {
                this.avaliacaoField = value;
                this.RaisePropertyChanged("avaliacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> solicitacaoatendida {
            get {
                return this.solicitacaoatendidaField;
            }
            set {
                this.solicitacaoatendidaField = value;
                this.RaisePropertyChanged("solicitacaoatendida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class ObterListaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObterListaRequestDados dadosField;
        
        private string siglaField;
        
        private string servicekeyField;
        
        private string hashField;
        
        private System.Nullable<int> posicaoinicialField;
        
        private System.Nullable<int> quantidadeField;
        
        private string parametro_testeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ObterListaRequestDados dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
                this.RaisePropertyChanged("dados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sigla {
            get {
                return this.siglaField;
            }
            set {
                this.siglaField = value;
                this.RaisePropertyChanged("sigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string servicekey {
            get {
                return this.servicekeyField;
            }
            set {
                this.servicekeyField = value;
                this.RaisePropertyChanged("servicekey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> posicaoinicial {
            get {
                return this.posicaoinicialField;
            }
            set {
                this.posicaoinicialField = value;
                this.RaisePropertyChanged("posicaoinicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string parametro_teste {
            get {
                return this.parametro_testeField;
            }
            set {
                this.parametro_testeField = value;
                this.RaisePropertyChanged("parametro_teste");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class ObterResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObterResultDados dadosField;
        
        private string statusRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ObterResultDados dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
                this.RaisePropertyChanged("dados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusRetorno {
            get {
                return this.statusRetornoField;
            }
            set {
                this.statusRetornoField = value;
                this.RaisePropertyChanged("statusRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class ObterRequestDados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bzpcodlancaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzpcodlanca {
            get {
                return this.bzpcodlancaField;
            }
            set {
                this.bzpcodlancaField = value;
                this.RaisePropertyChanged("bzpcodlanca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class ObterRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObterRequestDados dadosField;
        
        private string siglaField;
        
        private string servicekeyField;
        
        private string hashField;
        
        private System.Nullable<int> posicaoinicialField;
        
        private System.Nullable<int> quantidadeField;
        
        private string parametro_testeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ObterRequestDados dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
                this.RaisePropertyChanged("dados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sigla {
            get {
                return this.siglaField;
            }
            set {
                this.siglaField = value;
                this.RaisePropertyChanged("sigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string servicekey {
            get {
                return this.servicekeyField;
            }
            set {
                this.servicekeyField = value;
                this.RaisePropertyChanged("servicekey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> posicaoinicial {
            get {
                return this.posicaoinicialField;
            }
            set {
                this.posicaoinicialField = value;
                this.RaisePropertyChanged("posicaoinicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string parametro_teste {
            get {
                return this.parametro_testeField;
            }
            set {
                this.parametro_testeField = value;
                this.RaisePropertyChanged("parametro_teste");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class InserirResultDados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bzpcodlancaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bzpcodlanca {
            get {
                return this.bzpcodlancaField;
            }
            set {
                this.bzpcodlancaField = value;
                this.RaisePropertyChanged("bzpcodlanca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.mysuite1.com.br/empresas/safw/webservices/FormularioAvaliacaoAO.php")]
    public partial class InserirResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InserirResultDados dadosField;
        
        private string statusRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public InserirResultDados dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
                this.RaisePropertyChanged("dados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusRetorno {
            get {
                return this.statusRetornoField;
            }
            set {
                this.statusRetornoField = value;
                this.RaisePropertyChanged("statusRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FormularioAvaliacaoAOPortChannel : Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.FormularioAvaliacaoAOPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormularioAvaliacaoAOPortClient : System.ServiceModel.ClientBase<Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.FormularioAvaliacaoAOPort>, Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.FormularioAvaliacaoAOPort {
        
        public FormularioAvaliacaoAOPortClient() {
        }
        
        public FormularioAvaliacaoAOPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormularioAvaliacaoAOPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormularioAvaliacaoAOPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormularioAvaliacaoAOPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.InserirResult inserir(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.InserirRequest request) {
            return base.Channel.inserir(request);
        }
        
        public System.Threading.Tasks.Task<Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.InserirResult> inserirAsync(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.InserirRequest request) {
            return base.Channel.inserirAsync(request);
        }
        
        public Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterResult obter(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterRequest request) {
            return base.Channel.obter(request);
        }
        
        public System.Threading.Tasks.Task<Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterResult> obterAsync(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterRequest request) {
            return base.Channel.obterAsync(request);
        }
        
        public Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterListaResult obterLista(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterListaRequest request) {
            return base.Channel.obterLista(request);
        }
        
        public System.Threading.Tasks.Task<Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterListaResult> obterListaAsync(Brazip_ExtracaoDadosAutomaticamente.FormularioAvaliacaoAOBrazip.ObterListaRequest request) {
            return base.Channel.obterListaAsync(request);
        }
    }
}
